mert_user:
    resource: "@MertUserBundle/Resources/config/routing.yml"
    prefix:   /

mert_ticket:
    resource: "@MertTicketBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"